version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:7.5.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - logging
  kibana:
    image: kibana:7.5.1
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - logging
networks:
  logging:

