filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /Users/anthonyikeda/data/logs/spring/customerV1/application.log
      - /Users/anthonyikeda/data/logs/spring/customerV2/application.log
      - /Users/anthonyikeda/data/logs/spring/gateway/application.log

output.elasticsearch:
  hosts: ["localhost:9200"]

setup.kibana:
  host: "localhost:5601"
