spring:
  cloud:
    gateway:
      routes:
        - id: customer_v1
          uri: http://localhost:8070
          predicates:
            - Header=Accept,.*(version=1)
            - Path=/customer/*
          filters:
            - PrefixPath=/v1
        - id: customer_v2
          uri: http://localhost:8060
          predicates:
            - Path=/customer/*
            - Header=Accept,.*(version=2)
          filters:
            - PrefixPath=/v2
